import type { Database } from "@/lib/types";

const createdAt = "2026-09-01T12:00:00.000Z";

export function seedDatabase(): Database {
  return {
    performers: [
      {
        id: "maya-chen",
        name: "Maya Chen",
        category: "solo",
        bio: "Austin singer-songwriter with a hushed folk voice and looping guitar. Friday nights on the East Side, Sunday afternoons in coffeehouses.",
        city: "Austin, TX",
        genres: ["indie folk", "singer-songwriter"],
        createdAt,
        videos: [
          {
            id: "maya-v1",
            title: "Hotel Vegas late set",
            sourceType: "url",
            url: "https://www.youtube.com/watch?v=jfKfPfyJRdk",
          },
          {
            id: "maya-v2",
            title: "Living-room rehearsal",
            sourceType: "url",
            url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
          },
        ],
      },
      {
        id: "broken-strings",
        name: "The Broken Strings",
        category: "band",
        bio: "Four-piece garage rock from South Austin. Loud choruses, cheap amps, and a standing date with the Continental Club.",
        city: "Austin, TX",
        genres: ["garage rock", "indie"],
        createdAt,
        videos: [
          {
            id: "broken-v1",
            title: "Continental Club clip",
            sourceType: "url",
            url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
          },
          {
            id: "broken-v2",
            title: "Practice space take",
            sourceType: "url",
            url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
          },
        ],
      },
      {
        id: "dj-nova",
        name: "DJ Nova",
        category: "dj",
        bio: "Warehouse house and disco edits. Resident energy at Empire and after-hours on East 6th.",
        city: "Austin, TX",
        genres: ["house", "disco"],
        createdAt,
        videos: [
          {
            id: "nova-v1",
            title: "Empire Control Room",
            sourceType: "url",
            url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
          },
          {
            id: "nova-v2",
            title: "Sunset mix excerpt",
            sourceType: "url",
            url: "https://www.youtube.com/watch?v=5qap5aO4i9A",
          },
        ],
      },
      {
        id: "elijah-brooks",
        name: "Elijah Brooks",
        category: "solo",
        bio: "Jazz guitar, standards, and original ballads. Think hotel lobby at midnight, but warmer.",
        city: "Austin, TX",
        genres: ["jazz", "standards"],
        createdAt,
        videos: [
          {
            id: "elijah-v1",
            title: "C-Boy's trio night",
            sourceType: "url",
            url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
          },
        ],
      },
      {
        id: "velvet-static",
        name: "Velvet Static",
        category: "band",
        bio: "Dream-pop five-piece. Pedalboards, fog, and choruses that hang in the rafters at Mohawk.",
        city: "Austin, TX",
        genres: ["dream pop", "shoegaze"],
        createdAt,
        videos: [
          {
            id: "velvet-v1",
            title: "Mohawk indoor",
            sourceType: "url",
            url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
          },
          {
            id: "velvet-v2",
            title: "Demo reel",
            sourceType: "url",
            url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
          },
        ],
      },
      {
        id: "luna-park",
        name: "Luna Park",
        category: "dj",
        bio: "Hypnotic techno and late-night warehouse sets. Peak time starts after 1am.",
        city: "Austin, TX",
        genres: ["techno", "minimal"],
        createdAt,
        videos: [
          {
            id: "luna-v1",
            title: "Warehouse peak-time",
            sourceType: "url",
            url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
          },
        ],
      },
      {
        id: "nightbirds",
        name: "Rio & the Nightbirds",
        category: "band",
        bio: "Latin soul, cumbia, and Saturday-night horns. The dance floor fills before the second chorus.",
        city: "Austin, TX",
        genres: ["latin soul", "cumbia"],
        createdAt,
        videos: [
          {
            id: "rio-v1",
            title: "Stubb's patio",
            sourceType: "url",
            url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4",
          },
          {
            id: "rio-v2",
            title: "Horn section close-up",
            sourceType: "url",
            url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4",
          },
        ],
      },
      {
        id: "harper-quinn",
        name: "Harper Quinn",
        category: "solo",
        bio: "Alto, nylon-string guitar, and stories from the Drag. Quiet rooms only.",
        city: "Austin, TX",
        genres: ["folk", "americana"],
        createdAt,
        videos: [
          {
            id: "harper-v1",
            title: "Saxon Pub open mic",
            sourceType: "url",
            url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
          },
          {
            id: "harper-v2",
            title: "Porch take",
            sourceType: "url",
            url: "https://www.youtube.com/watch?v=lTRiuFIWV54",
          },
        ],
      },
      {
        id: "bassline-society",
        name: "Bassline Society",
        category: "dj",
        bio: "Hip-hop, bounce, and dirty south classics. Wedding-safe until midnight, then the crate flips.",
        city: "Austin, TX",
        genres: ["hip-hop", "bounce"],
        createdAt,
        videos: [
          {
            id: "bass-v1",
            title: "Parish club set",
            sourceType: "url",
            url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
          },
        ],
      },
      {
        id: "copper-notes",
        name: "The Copper Notes",
        category: "band",
        bio: "Pedal steel, two-part harmony, and honky-tonk heartbreak. White Horse regulars.",
        city: "Austin, TX",
        genres: ["americana", "honky-tonk"],
        createdAt,
        videos: [
          {
            id: "copper-v1",
            title: "White Horse two-step",
            sourceType: "url",
            url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
          },
          {
            id: "copper-v2",
            title: "Steel guitar feature",
            sourceType: "url",
            url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
          },
        ],
      },
    ],
    gigs: [
      {
        id: "gig-antones-maya",
        performerId: "maya-chen",
        title: "Late set at Antone's",
        description: "Solo looping set in the front room. Come early if you want a seat along the bar.",
        category: "solo",
        datetime: "2026-09-11T21:30:00-05:00",
        location: {
          lat: 30.2661,
          lng: -97.7396,
          label: "Antone's Nightclub, 305 E 5th St",
        },
        createdAt,
      },
      {
        id: "gig-stubbs-rio",
        performerId: "nightbirds",
        title: "Patio dance night",
        description: "Rio & the Nightbirds bring the horns outside. Food trucks stay open late.",
        category: "band",
        datetime: "2026-09-12T20:00:00-05:00",
        location: {
          lat: 30.2685,
          lng: -97.7362,
          label: "Stubb's BBQ, 801 Red River St",
        },
        createdAt,
      },
      {
        id: "gig-mohawk-velvet",
        performerId: "velvet-static",
        title: "Indoor / indoor",
        description: "Full band, fog, and the Mohawk indoor PA. Support TBA.",
        category: "band",
        datetime: "2026-09-13T22:00:00-05:00",
        location: {
          lat: 30.27,
          lng: -97.736,
          label: "Mohawk Austin, 912 Red River St",
        },
        createdAt,
      },
      {
        id: "gig-empire-nova",
        performerId: "dj-nova",
        title: "Disco edits until close",
        description: "Nova on the booth from 11 to 2. No guest list, just show up.",
        category: "dj",
        datetime: "2026-09-18T23:00:00-05:00",
        location: {
          lat: 30.2674,
          lng: -97.7366,
          label: "Empire Control Room, 606 E 7th St",
        },
        createdAt,
      },
      {
        id: "gig-continental-broken",
        performerId: "broken-strings",
        title: "Continental Club residency",
        description: "Monthly loud night. Earplugs at the merch table.",
        category: "band",
        datetime: "2026-09-19T21:00:00-05:00",
        location: {
          lat: 30.2478,
          lng: -97.7505,
          label: "Continental Club, 1315 S Congress Ave",
        },
        createdAt,
      },
      {
        id: "gig-cboy-elijah",
        performerId: "elijah-brooks",
        title: "Standards after dinner",
        description: "Trio format — guitar, upright, brushes. Table service stays open.",
        category: "solo",
        datetime: "2026-09-20T19:30:00-05:00",
        location: {
          lat: 30.245,
          lng: -97.7512,
          label: "C-Boy's Heart & Soul, 2008 S Congress Ave",
        },
        createdAt,
      },
      {
        id: "gig-saxon-harper",
        performerId: "harper-quinn",
        title: "Sunday songwriter hour",
        description: "New songs, old stories, and the Saxon sound system being kind.",
        category: "solo",
        datetime: "2026-09-27T18:00:00-05:00",
        location: {
          lat: 30.2553,
          lng: -97.7633,
          label: "The Saxon Pub, 1320 S Lamar Blvd",
        },
        createdAt,
      },
      {
        id: "gig-whitehorse-copper",
        performerId: "copper-notes",
        title: "Two-step Tuesday",
        description: "Dance lessons at 7, The Copper Notes at 8. Boots recommended.",
        category: "band",
        datetime: "2026-09-29T20:00:00-05:00",
        location: {
          lat: 30.2625,
          lng: -97.7258,
          label: "The White Horse, 500 Comal St",
        },
        createdAt,
      },
      {
        id: "gig-parish-bassline",
        performerId: "bassline-society",
        title: "Club night: crates out",
        description: "Hip-hop and bounce until last call. 21+.",
        category: "dj",
        datetime: "2026-10-02T22:30:00-05:00",
        location: {
          lat: 30.2672,
          lng: -97.74,
          label: "Parish, 214 E 6th St",
        },
        createdAt,
      },
      {
        id: "gig-hotelvegas-maya",
        performerId: "maya-chen",
        title: "East Side twilight",
        description: "Outdoor stage if the weather holds, inside if it doesn't.",
        category: "solo",
        datetime: "2026-10-03T19:00:00-05:00",
        location: {
          lat: 30.2622,
          lng: -97.7278,
          label: "Hotel Vegas, 1502 E 6th St",
        },
        createdAt,
      },
      {
        id: "gig-cheerup-luna",
        performerId: "luna-park",
        title: "After hours at Cheer Up",
        description: "Minimal techno in the backyard. Starts late, ends later.",
        category: "dj",
        datetime: "2026-10-09T00:30:00-05:00",
        location: {
          lat: 30.2694,
          lng: -97.7365,
          label: "Cheer Up Charlies, 900 Red River St",
        },
        createdAt,
      },
      {
        id: "gig-acl-velvet",
        performerId: "velvet-static",
        title: "Moody Theater warmup",
        description: "Special sit-down set before a touring bill. Limited GA.",
        category: "band",
        datetime: "2026-10-10T20:00:00-05:00",
        location: {
          lat: 30.2653,
          lng: -97.7472,
          label: "ACL Live at the Moody Theater, 310 W 2nd St",
        },
        createdAt,
      },
    ],
    bookings: [],
  };
}
